/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  Response400Code,
  Response400Code$inboundSchema,
  Response400Code$outboundSchema,
} from "./response400code.js";
import {
  Response400Type,
  Response400Type$inboundSchema,
  Response400Type$outboundSchema,
} from "./response400type.js";

/**
 * Bad Request
 */
export type PatchV2ObjectsObjectResponseBodyData = {
  statusCode: number;
  type: Response400Type;
  code: Response400Code;
  message: string;
};

/**
 * Bad Request
 */
export class PatchV2ObjectsObjectResponseBody extends Error {
  statusCode: number;
  type: Response400Type;
  code: Response400Code;

  /** The original data that was passed to this error instance. */
  data$: PatchV2ObjectsObjectResponseBodyData;

  constructor(err: PatchV2ObjectsObjectResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.statusCode = err.statusCode;
    this.type = err.type;
    this.code = err.code;

    this.name = "PatchV2ObjectsObjectResponseBody";
  }
}

/** @internal */
export const PatchV2ObjectsObjectResponseBody$inboundSchema: z.ZodType<
  PatchV2ObjectsObjectResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status_code: z.number(),
  type: Response400Type$inboundSchema,
  code: Response400Code$inboundSchema,
  message: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PatchV2ObjectsObjectResponseBody(remapped);
  });

/** @internal */
export type PatchV2ObjectsObjectResponseBody$Outbound = {
  status_code: number;
  type: string;
  code: string;
  message: string;
};

/** @internal */
export const PatchV2ObjectsObjectResponseBody$outboundSchema: z.ZodType<
  PatchV2ObjectsObjectResponseBody$Outbound,
  z.ZodTypeDef,
  PatchV2ObjectsObjectResponseBody
> = z.instanceof(PatchV2ObjectsObjectResponseBody)
  .transform(v => v.data$)
  .pipe(
    z.object({
      statusCode: z.number(),
      type: Response400Type$outboundSchema,
      code: Response400Code$outboundSchema,
      message: z.string(),
    }).transform((v) => {
      return remap$(v, {
        statusCode: "status_code",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ObjectsObjectResponseBody$ {
  /** @deprecated use `PatchV2ObjectsObjectResponseBody$inboundSchema` instead. */
  export const inboundSchema = PatchV2ObjectsObjectResponseBody$inboundSchema;
  /** @deprecated use `PatchV2ObjectsObjectResponseBody$outboundSchema` instead. */
  export const outboundSchema = PatchV2ObjectsObjectResponseBody$outboundSchema;
  /** @deprecated use `PatchV2ObjectsObjectResponseBody$Outbound` instead. */
  export type Outbound = PatchV2ObjectsObjectResponseBody$Outbound;
}
