/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const PatchV2TargetIdentifierAttributesAttributeCode = {
  SystemEditUnauthorized: "system_edit_unauthorized",
} as const;
export type PatchV2TargetIdentifierAttributesAttributeCode = ClosedEnum<
  typeof PatchV2TargetIdentifierAttributesAttributeCode
>;

/** @internal */
export const PatchV2TargetIdentifierAttributesAttributeCode$inboundSchema:
  z.ZodNativeEnum<typeof PatchV2TargetIdentifierAttributesAttributeCode> = z
    .nativeEnum(PatchV2TargetIdentifierAttributesAttributeCode);

/** @internal */
export const PatchV2TargetIdentifierAttributesAttributeCode$outboundSchema:
  z.ZodNativeEnum<typeof PatchV2TargetIdentifierAttributesAttributeCode> =
    PatchV2TargetIdentifierAttributesAttributeCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2TargetIdentifierAttributesAttributeCode$ {
  /** @deprecated use `PatchV2TargetIdentifierAttributesAttributeCode$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2TargetIdentifierAttributesAttributeCode$inboundSchema;
  /** @deprecated use `PatchV2TargetIdentifierAttributesAttributeCode$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2TargetIdentifierAttributesAttributeCode$outboundSchema;
}
