/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  PostV2ObjectsObjectRecordsQueryCode,
  PostV2ObjectsObjectRecordsQueryCode$inboundSchema,
  PostV2ObjectsObjectRecordsQueryCode$outboundSchema,
} from "./postv2objectsobjectrecordsquerycode.js";
import {
  Response400Type,
  Response400Type$inboundSchema,
  Response400Type$outboundSchema,
} from "./response400type.js";

/**
 * Bad Request
 */
export type PostV2ObjectsObjectRecordsQueryResponseBodyData = {
  statusCode: number;
  type: Response400Type;
  code: PostV2ObjectsObjectRecordsQueryCode;
  message: string;
};

/**
 * Bad Request
 */
export class PostV2ObjectsObjectRecordsQueryResponseBody extends Error {
  statusCode: number;
  type: Response400Type;
  code: PostV2ObjectsObjectRecordsQueryCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ObjectsObjectRecordsQueryResponseBodyData;

  constructor(err: PostV2ObjectsObjectRecordsQueryResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.statusCode = err.statusCode;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ObjectsObjectRecordsQueryResponseBody";
  }
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryResponseBody$inboundSchema:
  z.ZodType<
    PostV2ObjectsObjectRecordsQueryResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status_code: z.number(),
    type: Response400Type$inboundSchema,
    code: PostV2ObjectsObjectRecordsQueryCode$inboundSchema,
    message: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2ObjectsObjectRecordsQueryResponseBody(remapped);
    });

/** @internal */
export type PostV2ObjectsObjectRecordsQueryResponseBody$Outbound = {
  status_code: number;
  type: string;
  code: string;
  message: string;
};

/** @internal */
export const PostV2ObjectsObjectRecordsQueryResponseBody$outboundSchema:
  z.ZodType<
    PostV2ObjectsObjectRecordsQueryResponseBody$Outbound,
    z.ZodTypeDef,
    PostV2ObjectsObjectRecordsQueryResponseBody
  > = z.instanceof(PostV2ObjectsObjectRecordsQueryResponseBody)
    .transform(v => v.data$)
    .pipe(
      z.object({
        statusCode: z.number(),
        type: Response400Type$outboundSchema,
        code: PostV2ObjectsObjectRecordsQueryCode$outboundSchema,
        message: z.string(),
      }).transform((v) => {
        return remap$(v, {
          statusCode: "status_code",
        });
      }),
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ObjectsObjectRecordsQueryResponseBody$ {
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ObjectsObjectRecordsQueryResponseBody$inboundSchema;
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ObjectsObjectRecordsQueryResponseBody$outboundSchema;
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryResponseBody$Outbound` instead. */
  export type Outbound = PostV2ObjectsObjectRecordsQueryResponseBody$Outbound;
}
