/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export const PostV2ObjectsObjectRecordsQueryRecordsType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type PostV2ObjectsObjectRecordsQueryRecordsType = ClosedEnum<
  typeof PostV2ObjectsObjectRecordsQueryRecordsType
>;

export const PostV2ObjectsObjectRecordsQueryRecordsCode = {
  NotFound: "not_found",
} as const;
export type PostV2ObjectsObjectRecordsQueryRecordsCode = ClosedEnum<
  typeof PostV2ObjectsObjectRecordsQueryRecordsCode
>;

/**
 * Not Found
 */
export type PostV2ObjectsObjectRecordsQueryRecordsResponseBodyData = {
  statusCode: number;
  type: PostV2ObjectsObjectRecordsQueryRecordsType;
  code: PostV2ObjectsObjectRecordsQueryRecordsCode;
  message: string;
};

/**
 * Not Found
 */
export class PostV2ObjectsObjectRecordsQueryRecordsResponseBody extends Error {
  statusCode: number;
  type: PostV2ObjectsObjectRecordsQueryRecordsType;
  code: PostV2ObjectsObjectRecordsQueryRecordsCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ObjectsObjectRecordsQueryRecordsResponseBodyData;

  constructor(err: PostV2ObjectsObjectRecordsQueryRecordsResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.statusCode = err.statusCode;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ObjectsObjectRecordsQueryRecordsResponseBody";
  }
}

export const PostV2ObjectsObjectRecordsQueryType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type PostV2ObjectsObjectRecordsQueryType = ClosedEnum<
  typeof PostV2ObjectsObjectRecordsQueryType
>;

export const PostV2ObjectsObjectRecordsQueryCode = {
  FilterError: "filter_error",
} as const;
export type PostV2ObjectsObjectRecordsQueryCode = ClosedEnum<
  typeof PostV2ObjectsObjectRecordsQueryCode
>;

/**
 * Bad Request
 */
export type PostV2ObjectsObjectRecordsQueryResponseBodyData = {
  statusCode: number;
  type: PostV2ObjectsObjectRecordsQueryType;
  code: PostV2ObjectsObjectRecordsQueryCode;
  message: string;
};

/**
 * Bad Request
 */
export class PostV2ObjectsObjectRecordsQueryResponseBody extends Error {
  statusCode: number;
  type: PostV2ObjectsObjectRecordsQueryType;
  code: PostV2ObjectsObjectRecordsQueryCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ObjectsObjectRecordsQueryResponseBodyData;

  constructor(err: PostV2ObjectsObjectRecordsQueryResponseBodyData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    this.statusCode = err.statusCode;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ObjectsObjectRecordsQueryResponseBody";
  }
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryRecordsType$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ObjectsObjectRecordsQueryRecordsType> = z
    .nativeEnum(PostV2ObjectsObjectRecordsQueryRecordsType);

/** @internal */
export const PostV2ObjectsObjectRecordsQueryRecordsType$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ObjectsObjectRecordsQueryRecordsType> =
    PostV2ObjectsObjectRecordsQueryRecordsType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ObjectsObjectRecordsQueryRecordsType$ {
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryRecordsType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ObjectsObjectRecordsQueryRecordsType$inboundSchema;
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryRecordsType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ObjectsObjectRecordsQueryRecordsType$outboundSchema;
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryRecordsCode$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ObjectsObjectRecordsQueryRecordsCode> = z
    .nativeEnum(PostV2ObjectsObjectRecordsQueryRecordsCode);

/** @internal */
export const PostV2ObjectsObjectRecordsQueryRecordsCode$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ObjectsObjectRecordsQueryRecordsCode> =
    PostV2ObjectsObjectRecordsQueryRecordsCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ObjectsObjectRecordsQueryRecordsCode$ {
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryRecordsCode$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ObjectsObjectRecordsQueryRecordsCode$inboundSchema;
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryRecordsCode$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ObjectsObjectRecordsQueryRecordsCode$outboundSchema;
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryRecordsResponseBody$inboundSchema:
  z.ZodType<
    PostV2ObjectsObjectRecordsQueryRecordsResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status_code: z.number(),
    type: PostV2ObjectsObjectRecordsQueryRecordsType$inboundSchema,
    code: PostV2ObjectsObjectRecordsQueryRecordsCode$inboundSchema,
    message: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2ObjectsObjectRecordsQueryRecordsResponseBody(remapped);
    });

/** @internal */
export type PostV2ObjectsObjectRecordsQueryRecordsResponseBody$Outbound = {
  status_code: number;
  type: string;
  code: string;
  message: string;
};

/** @internal */
export const PostV2ObjectsObjectRecordsQueryRecordsResponseBody$outboundSchema:
  z.ZodType<
    PostV2ObjectsObjectRecordsQueryRecordsResponseBody$Outbound,
    z.ZodTypeDef,
    PostV2ObjectsObjectRecordsQueryRecordsResponseBody
  > = z.instanceof(PostV2ObjectsObjectRecordsQueryRecordsResponseBody)
    .transform(v => v.data$)
    .pipe(
      z.object({
        statusCode: z.number(),
        type: PostV2ObjectsObjectRecordsQueryRecordsType$outboundSchema,
        code: PostV2ObjectsObjectRecordsQueryRecordsCode$outboundSchema,
        message: z.string(),
      }).transform((v) => {
        return remap$(v, {
          statusCode: "status_code",
        });
      }),
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ObjectsObjectRecordsQueryRecordsResponseBody$ {
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryRecordsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ObjectsObjectRecordsQueryRecordsResponseBody$inboundSchema;
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryRecordsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ObjectsObjectRecordsQueryRecordsResponseBody$outboundSchema;
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryRecordsResponseBody$Outbound` instead. */
  export type Outbound =
    PostV2ObjectsObjectRecordsQueryRecordsResponseBody$Outbound;
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryType$inboundSchema: z.ZodNativeEnum<
  typeof PostV2ObjectsObjectRecordsQueryType
> = z.nativeEnum(PostV2ObjectsObjectRecordsQueryType);

/** @internal */
export const PostV2ObjectsObjectRecordsQueryType$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ObjectsObjectRecordsQueryType> =
    PostV2ObjectsObjectRecordsQueryType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ObjectsObjectRecordsQueryType$ {
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ObjectsObjectRecordsQueryType$inboundSchema;
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ObjectsObjectRecordsQueryType$outboundSchema;
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryCode$inboundSchema: z.ZodNativeEnum<
  typeof PostV2ObjectsObjectRecordsQueryCode
> = z.nativeEnum(PostV2ObjectsObjectRecordsQueryCode);

/** @internal */
export const PostV2ObjectsObjectRecordsQueryCode$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ObjectsObjectRecordsQueryCode> =
    PostV2ObjectsObjectRecordsQueryCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ObjectsObjectRecordsQueryCode$ {
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryCode$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ObjectsObjectRecordsQueryCode$inboundSchema;
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryCode$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ObjectsObjectRecordsQueryCode$outboundSchema;
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryResponseBody$inboundSchema:
  z.ZodType<
    PostV2ObjectsObjectRecordsQueryResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status_code: z.number(),
    type: PostV2ObjectsObjectRecordsQueryType$inboundSchema,
    code: PostV2ObjectsObjectRecordsQueryCode$inboundSchema,
    message: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2ObjectsObjectRecordsQueryResponseBody(remapped);
    });

/** @internal */
export type PostV2ObjectsObjectRecordsQueryResponseBody$Outbound = {
  status_code: number;
  type: string;
  code: string;
  message: string;
};

/** @internal */
export const PostV2ObjectsObjectRecordsQueryResponseBody$outboundSchema:
  z.ZodType<
    PostV2ObjectsObjectRecordsQueryResponseBody$Outbound,
    z.ZodTypeDef,
    PostV2ObjectsObjectRecordsQueryResponseBody
  > = z.instanceof(PostV2ObjectsObjectRecordsQueryResponseBody)
    .transform(v => v.data$)
    .pipe(
      z.object({
        statusCode: z.number(),
        type: PostV2ObjectsObjectRecordsQueryType$outboundSchema,
        code: PostV2ObjectsObjectRecordsQueryCode$outboundSchema,
        message: z.string(),
      }).transform((v) => {
        return remap$(v, {
          statusCode: "status_code",
        });
      }),
    );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ObjectsObjectRecordsQueryResponseBody$ {
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ObjectsObjectRecordsQueryResponseBody$inboundSchema;
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ObjectsObjectRecordsQueryResponseBody$outboundSchema;
  /** @deprecated use `PostV2ObjectsObjectRecordsQueryResponseBody$Outbound` instead. */
  export type Outbound = PostV2ObjectsObjectRecordsQueryResponseBody$Outbound;
}
