/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ResponseCode = {
  NotFound: "not_found",
} as const;
export type ResponseCode = ClosedEnum<typeof ResponseCode>;

/** @internal */
export const ResponseCode$inboundSchema: z.ZodNativeEnum<typeof ResponseCode> =
  z.nativeEnum(ResponseCode);

/** @internal */
export const ResponseCode$outboundSchema: z.ZodNativeEnum<typeof ResponseCode> =
  ResponseCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseCode$ {
  /** @deprecated use `ResponseCode$inboundSchema` instead. */
  export const inboundSchema = ResponseCode$inboundSchema;
  /** @deprecated use `ResponseCode$outboundSchema` instead. */
  export const outboundSchema = ResponseCode$outboundSchema;
}
