/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const Response400Code = {
  ValidationType: "validation_type",
} as const;
export type Response400Code = ClosedEnum<typeof Response400Code>;

/** @internal */
export const Response400Code$inboundSchema: z.ZodNativeEnum<
  typeof Response400Code
> = z.nativeEnum(Response400Code);

/** @internal */
export const Response400Code$outboundSchema: z.ZodNativeEnum<
  typeof Response400Code
> = Response400Code$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Response400Code$ {
  /** @deprecated use `Response400Code$inboundSchema` instead. */
  export const inboundSchema = Response400Code$inboundSchema;
  /** @deprecated use `Response400Code$outboundSchema` instead. */
  export const outboundSchema = Response400Code$outboundSchema;
}
