/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { attributesPostV2TargetIdentifierAttributesAttributeOptions } from "../../funcs/attributesPostV2TargetIdentifierAttributesAttributeOptions.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request:
    operations
      .PostV2TargetIdentifierAttributesAttributeOptionsRequest$inboundSchema,
};

export const tool$attributesPostV2TargetIdentifierAttributesAttributeOptions:
  ToolDefinition<typeof args> = {
    name: "attributes-post-v2-target-identifier-attributes-attribute-options",
    description: `Create a select option

Adds a select option to a select attribute on an object or a list.

Required scopes: \`object_configuration:read-write\`.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] =
        await attributesPostV2TargetIdentifierAttributesAttributeOptions(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
