/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { listsGetV2ListsList } from "../../funcs/listsGetV2ListsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetV2ListsListRequest$inboundSchema,
};

export const tool$listsGetV2ListsList: ToolDefinition<typeof args> = {
  name: "lists-get-v2-lists-list",
  description: `Get a list

Gets a single list in your workspace that your access token has access to.

Required scopes: \`list_configuration:read\`.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await listsGetV2ListsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
