/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { recordsDeleteV2ObjectsObjectRecordsRecordId } from "../../funcs/recordsDeleteV2ObjectsObjectRecordsRecordId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteV2ObjectsObjectRecordsRecordIdRequest$inboundSchema,
};

export const tool$recordsDeleteV2ObjectsObjectRecordsRecordId: ToolDefinition<
  typeof args
> = {
  name: "records-delete-v2-objects-object-records-record-id",
  description: `Delete a record

Deletes a single record (e.g. a company or person) by ID.

Required scopes: \`object_configuration:read\`, \`record_permission:read-write\`.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await recordsDeleteV2ObjectsObjectRecordsRecordId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
