/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspaceMembersGetV2WorkspaceMembers } from "../../funcs/workspaceMembersGetV2WorkspaceMembers.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$workspaceMembersGetV2WorkspaceMembers: ToolDefinition = {
  name: "workspace-members-get-v2-workspace-members",
  description: `List workspace members

Lists all workspace members in the workspace.

Required scopes: \`user_management:read\`.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await workspaceMembersGetV2WorkspaceMembers(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
