/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  InvalidateQueryFilters,
  QueryClient,
  QueryFunctionContext,
  QueryKey,
  useQuery,
  UseQueryResult,
  useSuspenseQuery,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { AttioCore } from "../core.js";
import { attributesListSelectOptions } from "../funcs/attributesListSelectOptions.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useAttioContext } from "./_context.js";
import {
  QueryHookOptions,
  SuspenseQueryHookOptions,
  TupleToPrefixes,
} from "./_types.js";

export type AttributesListSelectOptionsQueryData =
  operations.GetV2TargetIdentifierAttributesAttributeOptionsResponseBody;

/**
 * List select options
 *
 * @remarks
 * Lists all select options for a particular attribute on either an object or a list.
 *
 * Required scopes: `object_configuration:read`.
 */
export function useAttributesListSelectOptions(
  request: operations.GetV2TargetIdentifierAttributesAttributeOptionsRequest,
  options?: QueryHookOptions<AttributesListSelectOptionsQueryData>,
): UseQueryResult<AttributesListSelectOptionsQueryData, Error> {
  const client = useAttioContext();
  return useQuery({
    ...buildAttributesListSelectOptionsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

/**
 * List select options
 *
 * @remarks
 * Lists all select options for a particular attribute on either an object or a list.
 *
 * Required scopes: `object_configuration:read`.
 */
export function useAttributesListSelectOptionsSuspense(
  request: operations.GetV2TargetIdentifierAttributesAttributeOptionsRequest,
  options?: SuspenseQueryHookOptions<AttributesListSelectOptionsQueryData>,
): UseSuspenseQueryResult<AttributesListSelectOptionsQueryData, Error> {
  const client = useAttioContext();
  return useSuspenseQuery({
    ...buildAttributesListSelectOptionsQuery(
      client,
      request,
      options,
    ),
    ...options,
  });
}

export function prefetchAttributesListSelectOptions(
  queryClient: QueryClient,
  client$: AttioCore,
  request: operations.GetV2TargetIdentifierAttributesAttributeOptionsRequest,
): Promise<void> {
  return queryClient.prefetchQuery({
    ...buildAttributesListSelectOptionsQuery(
      client$,
      request,
    ),
  });
}

export function setAttributesListSelectOptionsData(
  client: QueryClient,
  queryKeyBase: [
    target:
      operations.GetV2TargetIdentifierAttributesAttributeOptionsPathParamTarget,
    identifier: string,
    attribute: string,
    parameters: { showArchived?: boolean | undefined },
  ],
  data: AttributesListSelectOptionsQueryData,
): AttributesListSelectOptionsQueryData | undefined {
  const key = queryKeyAttributesListSelectOptions(...queryKeyBase);

  return client.setQueryData<AttributesListSelectOptionsQueryData>(key, data);
}

export function invalidateAttributesListSelectOptions(
  client: QueryClient,
  queryKeyBase: TupleToPrefixes<
    [
      target:
        operations.GetV2TargetIdentifierAttributesAttributeOptionsPathParamTarget,
      identifier: string,
      attribute: string,
      parameters: { showArchived?: boolean | undefined },
    ]
  >,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["attio-js", "Attributes", "listSelectOptions", ...queryKeyBase],
  });
}

export function invalidateAllAttributesListSelectOptions(
  client: QueryClient,
  filters?: Omit<InvalidateQueryFilters, "queryKey" | "predicate" | "exact">,
): Promise<void> {
  return client.invalidateQueries({
    ...filters,
    queryKey: ["attio-js", "Attributes", "listSelectOptions"],
  });
}

export function buildAttributesListSelectOptionsQuery(
  client$: AttioCore,
  request: operations.GetV2TargetIdentifierAttributesAttributeOptionsRequest,
  options?: RequestOptions,
): {
  queryKey: QueryKey;
  queryFn: (
    context: QueryFunctionContext,
  ) => Promise<AttributesListSelectOptionsQueryData>;
} {
  return {
    queryKey: queryKeyAttributesListSelectOptions(
      request.target,
      request.identifier,
      request.attribute,
      { showArchived: request.showArchived },
    ),
    queryFn: async function attributesListSelectOptionsQueryFn(
      ctx,
    ): Promise<AttributesListSelectOptionsQueryData> {
      const sig = combineSignals(ctx.signal, options?.fetchOptions?.signal);
      const mergedOptions = {
        ...options,
        fetchOptions: { ...options?.fetchOptions, signal: sig },
      };

      return unwrapAsync(attributesListSelectOptions(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}

export function queryKeyAttributesListSelectOptions(
  target:
    operations.GetV2TargetIdentifierAttributesAttributeOptionsPathParamTarget,
  identifier: string,
  attribute: string,
  parameters: { showArchived?: boolean | undefined },
): QueryKey {
  return [
    "attio-js",
    "Attributes",
    "listSelectOptions",
    target,
    identifier,
    attribute,
    parameters,
  ];
}
