/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  MutationKey,
  useMutation,
  UseMutationResult,
} from "@tanstack/react-query";
import { AttioCore } from "../core.js";
import { recordsCreate } from "../funcs/recordsCreate.js";
import { combineSignals } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { useAttioContext } from "./_context.js";
import { MutationHookOptions } from "./_types.js";

export type RecordsCreateMutationVariables = {
  request: operations.PostV2ObjectsObjectRecordsRequest;
  options?: RequestOptions;
};

export type RecordsCreateMutationData =
  operations.PostV2ObjectsObjectRecordsResponseBody;

/**
 * Create a record
 *
 * @remarks
 * Creates a new person, company or other record. This endpoint will throw on conflicts of unique attributes. If you would prefer to update records on conflicts, please use the [Assert record endpoint](/reference/put_v2-objects-object-records) instead.
 *
 * Required scopes: `record_permission:read-write`, `object_configuration:read`.
 */
export function useRecordsCreateMutation(
  options?: MutationHookOptions<
    RecordsCreateMutationData,
    Error,
    RecordsCreateMutationVariables
  >,
): UseMutationResult<
  RecordsCreateMutationData,
  Error,
  RecordsCreateMutationVariables
> {
  const client = useAttioContext();
  return useMutation({
    ...buildRecordsCreateMutation(client, options),
    ...options,
  });
}

export function mutationKeyRecordsCreate(): MutationKey {
  return ["attio-js", "Records", "create"];
}

export function buildRecordsCreateMutation(
  client$: AttioCore,
  hookOptions?: RequestOptions,
): {
  mutationKey: MutationKey;
  mutationFn: (
    variables: RecordsCreateMutationVariables,
  ) => Promise<RecordsCreateMutationData>;
} {
  return {
    mutationKey: mutationKeyRecordsCreate(),
    mutationFn: function recordsCreateMutationFn({
      request,
      options,
    }): Promise<RecordsCreateMutationData> {
      const mergedOptions = {
        ...hookOptions,
        ...options,
        fetchOptions: {
          ...hookOptions?.fetchOptions,
          ...options?.fetchOptions,
          signal: combineSignals(
            hookOptions?.fetchOptions?.signal,
            options?.fetchOptions?.signal,
          ),
        },
      };
      return unwrapAsync(recordsCreate(
        client$,
        request,
        mergedOptions,
      ));
    },
  };
}
