/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AttioCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  GetV2TargetIdentifierAttributesAttributeNotFoundError,
  GetV2TargetIdentifierAttributesAttributeNotFoundError$inboundSchema,
  SystemEditUnauthorizedError,
  SystemEditUnauthorizedError$inboundSchema,
} from "../models/errors/getv2objectsobject.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  PatchV2TargetIdentifierAttributesAttributeRequest,
  PatchV2TargetIdentifierAttributesAttributeRequest$outboundSchema,
  PatchV2TargetIdentifierAttributesAttributeResponse,
  PatchV2TargetIdentifierAttributesAttributeResponse$inboundSchema,
} from "../models/operations/patchv2targetidentifierattributesattribute.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Update an attribute
 *
 * @remarks
 * Updates a single attribute on a given object or list.
 *
 * Required scopes: `object_configuration:read-write`.
 */
export function attributesUpdate(
  client: AttioCore,
  request: PatchV2TargetIdentifierAttributesAttributeRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    PatchV2TargetIdentifierAttributesAttributeResponse,
    | SystemEditUnauthorizedError
    | GetV2TargetIdentifierAttributesAttributeNotFoundError
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: AttioCore,
  request: PatchV2TargetIdentifierAttributesAttributeRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      PatchV2TargetIdentifierAttributesAttributeResponse,
      | SystemEditUnauthorizedError
      | GetV2TargetIdentifierAttributesAttributeNotFoundError
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) =>
      PatchV2TargetIdentifierAttributesAttributeRequest$outboundSchema.parse(
        value,
      ),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload.RequestBody, { explode: true });

  const pathParams = {
    attribute: encodeSimple("attribute", payload.attribute, {
      explode: false,
      charEncoding: "percent",
    }),
    identifier: encodeSimple("identifier", payload.identifier, {
      explode: false,
      charEncoding: "percent",
    }),
    target: encodeSimple("target", payload.target, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/v2/{target}/{identifier}/attributes/{attribute}")(
    pathParams,
  );

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.apiKey);
  const securityInput = secConfig == null ? {} : { apiKey: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "patch_/v2/{target}/{identifier}/attributes/{attribute}",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.apiKey,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "PATCH",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["400", "404", "4XX", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    PatchV2TargetIdentifierAttributesAttributeResponse,
    | SystemEditUnauthorizedError
    | GetV2TargetIdentifierAttributesAttributeNotFoundError
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(
      200,
      PatchV2TargetIdentifierAttributesAttributeResponse$inboundSchema,
    ),
    M.jsonErr(400, SystemEditUnauthorizedError$inboundSchema),
    M.jsonErr(
      404,
      GetV2TargetIdentifierAttributesAttributeNotFoundError$inboundSchema,
    ),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
