/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { entriesAttributesValuesList } from "../funcs/entriesAttributesValuesList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import {
  GetV2ListsListEntriesEntryIdAttributesAttributeValuesRequest,
  GetV2ListsListEntriesEntryIdAttributesAttributeValuesResponse,
} from "../models/operations/getv2listslistentriesentryidattributesattributevalues.js";
import { unwrapAsync } from "../types/fp.js";

export class Values extends ClientSDK {
  /**
   * List attribute values for a list entry
   *
   * @remarks
   * Gets all values for a given attribute on a list entry. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.
   *
   * Required scopes: `list_entry:read`, `list_configuration:read`.
   */
  async list(
    request: GetV2ListsListEntriesEntryIdAttributesAttributeValuesRequest,
    options?: RequestOptions,
  ): Promise<GetV2ListsListEntriesEntryIdAttributesAttributeValuesResponse> {
    return unwrapAsync(entriesAttributesValuesList(
      this,
      request,
      options,
    ));
  }
}
