workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Attio API:
        inputs:
            - location: https://developers.attio.com/openapi/655e2ce3ace07f065aa1dd14
        overlays:
            - location: .speakeasy\speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/d-stoll/attio-js/attio-api
targets:
    attio:
        target: typescript
        source: Attio API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/d-stoll/attio-js/attio-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
