/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV2TasksTaskIdRequest = {
  taskId: string;
};

/**
 * Success
 */
export type DeleteV2TasksTaskIdResponseBody = {};

/** @internal */
export const DeleteV2TasksTaskIdRequest$inboundSchema: z.ZodType<
  DeleteV2TasksTaskIdRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  task_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "task_id": "taskId",
  });
});

/** @internal */
export type DeleteV2TasksTaskIdRequest$Outbound = {
  task_id: string;
};

/** @internal */
export const DeleteV2TasksTaskIdRequest$outboundSchema: z.ZodType<
  DeleteV2TasksTaskIdRequest$Outbound,
  z.ZodTypeDef,
  DeleteV2TasksTaskIdRequest
> = z.object({
  taskId: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteV2TasksTaskIdRequest$ {
  /** @deprecated use `DeleteV2TasksTaskIdRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteV2TasksTaskIdRequest$inboundSchema;
  /** @deprecated use `DeleteV2TasksTaskIdRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteV2TasksTaskIdRequest$outboundSchema;
  /** @deprecated use `DeleteV2TasksTaskIdRequest$Outbound` instead. */
  export type Outbound = DeleteV2TasksTaskIdRequest$Outbound;
}

export function deleteV2TasksTaskIdRequestToJSON(
  deleteV2TasksTaskIdRequest: DeleteV2TasksTaskIdRequest,
): string {
  return JSON.stringify(
    DeleteV2TasksTaskIdRequest$outboundSchema.parse(deleteV2TasksTaskIdRequest),
  );
}

export function deleteV2TasksTaskIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV2TasksTaskIdRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV2TasksTaskIdRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV2TasksTaskIdRequest' from JSON`,
  );
}

/** @internal */
export const DeleteV2TasksTaskIdResponseBody$inboundSchema: z.ZodType<
  DeleteV2TasksTaskIdResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type DeleteV2TasksTaskIdResponseBody$Outbound = {};

/** @internal */
export const DeleteV2TasksTaskIdResponseBody$outboundSchema: z.ZodType<
  DeleteV2TasksTaskIdResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteV2TasksTaskIdResponseBody
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteV2TasksTaskIdResponseBody$ {
  /** @deprecated use `DeleteV2TasksTaskIdResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeleteV2TasksTaskIdResponseBody$inboundSchema;
  /** @deprecated use `DeleteV2TasksTaskIdResponseBody$outboundSchema` instead. */
  export const outboundSchema = DeleteV2TasksTaskIdResponseBody$outboundSchema;
  /** @deprecated use `DeleteV2TasksTaskIdResponseBody$Outbound` instead. */
  export type Outbound = DeleteV2TasksTaskIdResponseBody$Outbound;
}

export function deleteV2TasksTaskIdResponseBodyToJSON(
  deleteV2TasksTaskIdResponseBody: DeleteV2TasksTaskIdResponseBody,
): string {
  return JSON.stringify(
    DeleteV2TasksTaskIdResponseBody$outboundSchema.parse(
      deleteV2TasksTaskIdResponseBody,
    ),
  );
}

export function deleteV2TasksTaskIdResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV2TasksTaskIdResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV2TasksTaskIdResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV2TasksTaskIdResponseBody' from JSON`,
  );
}
