/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2ObjectsObjectRequest = {
  object: string;
};

/**
 * Success
 */
export type GetV2ObjectsObjectResponseBody = {
  data: components.ObjectT;
};

/** @internal */
export const GetV2ObjectsObjectRequest$inboundSchema: z.ZodType<
  GetV2ObjectsObjectRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string(),
});

/** @internal */
export type GetV2ObjectsObjectRequest$Outbound = {
  object: string;
};

/** @internal */
export const GetV2ObjectsObjectRequest$outboundSchema: z.ZodType<
  GetV2ObjectsObjectRequest$Outbound,
  z.ZodTypeDef,
  GetV2ObjectsObjectRequest
> = z.object({
  object: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ObjectsObjectRequest$ {
  /** @deprecated use `GetV2ObjectsObjectRequest$inboundSchema` instead. */
  export const inboundSchema = GetV2ObjectsObjectRequest$inboundSchema;
  /** @deprecated use `GetV2ObjectsObjectRequest$outboundSchema` instead. */
  export const outboundSchema = GetV2ObjectsObjectRequest$outboundSchema;
  /** @deprecated use `GetV2ObjectsObjectRequest$Outbound` instead. */
  export type Outbound = GetV2ObjectsObjectRequest$Outbound;
}

export function getV2ObjectsObjectRequestToJSON(
  getV2ObjectsObjectRequest: GetV2ObjectsObjectRequest,
): string {
  return JSON.stringify(
    GetV2ObjectsObjectRequest$outboundSchema.parse(getV2ObjectsObjectRequest),
  );
}

export function getV2ObjectsObjectRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ObjectsObjectRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2ObjectsObjectRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ObjectsObjectRequest' from JSON`,
  );
}

/** @internal */
export const GetV2ObjectsObjectResponseBody$inboundSchema: z.ZodType<
  GetV2ObjectsObjectResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: components.ObjectT$inboundSchema,
});

/** @internal */
export type GetV2ObjectsObjectResponseBody$Outbound = {
  data: components.ObjectT$Outbound;
};

/** @internal */
export const GetV2ObjectsObjectResponseBody$outboundSchema: z.ZodType<
  GetV2ObjectsObjectResponseBody$Outbound,
  z.ZodTypeDef,
  GetV2ObjectsObjectResponseBody
> = z.object({
  data: components.ObjectT$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ObjectsObjectResponseBody$ {
  /** @deprecated use `GetV2ObjectsObjectResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetV2ObjectsObjectResponseBody$inboundSchema;
  /** @deprecated use `GetV2ObjectsObjectResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetV2ObjectsObjectResponseBody$outboundSchema;
  /** @deprecated use `GetV2ObjectsObjectResponseBody$Outbound` instead. */
  export type Outbound = GetV2ObjectsObjectResponseBody$Outbound;
}

export function getV2ObjectsObjectResponseBodyToJSON(
  getV2ObjectsObjectResponseBody: GetV2ObjectsObjectResponseBody,
): string {
  return JSON.stringify(
    GetV2ObjectsObjectResponseBody$outboundSchema.parse(
      getV2ObjectsObjectResponseBody,
    ),
  );
}

export function getV2ObjectsObjectResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ObjectsObjectResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2ObjectsObjectResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ObjectsObjectResponseBody' from JSON`,
  );
}
